from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
TAURI_ROOT = REPO_ROOT / "code" / "desktop_tauri" / "src-tauri"
LIB_RS = TAURI_ROOT / "src" / "lib.rs"
COMMAND_MANIFEST = TAURI_ROOT / "src" / "app_command_manifest.rs"


def test_next002_exposes_explicit_dual_track_lifecycle_without_a_mixed_command() -> None:
    lib_source = LIB_RS.read_text(encoding="utf-8")
    command_source = COMMAND_MANIFEST.read_text(encoding="utf-8")

    required_commands = (
        "dual_track_adapter_start",
        "dual_track_adapter_status",
        "dual_track_adapter_collect_events",
        "dual_track_adapter_stop",
        "dual_track_adapter_cleanup",
        "mic_adapter_cleanup",
        "system_audio_adapter_cleanup",
    )
    for command in required_commands:
        assert f'"{command}"' in command_source
        assert command in lib_source

    assert "mixed_audio_adapter" not in lib_source
    assert "mixed_audio_adapter" not in command_source
    assert "mixed_audio_created: false" in lib_source


def test_next002_commands_are_wired_to_one_shared_dual_track_coordinator() -> None:
    lib_source = LIB_RS.read_text(encoding="utf-8")

    assert "DualTrackCaptureCoordinator" in lib_source
    assert "claim_dual_track" in lib_source
    assert "CaptureTrack::Microphone" in lib_source
    assert "CaptureTrack::SystemAudio" in lib_source
    assert "app.manage(capture_coordinator);" in lib_source
    assert "app.manage(capture_arbiter);" not in lib_source


def test_next002_keeps_each_track_local_and_explicitly_identified() -> None:
    mic_source = (TAURI_ROOT / "src" / "native_mic_capture_runtime.rs").read_text(
        encoding="utf-8"
    )
    system_source = (
        TAURI_ROOT / "src" / "native_system_audio_capture_runtime.rs"
    ).read_text(encoding="utf-8")

    for source, track_id in (
        (mic_source, 'track_id: "microphone"'),
        (system_source, 'track_id: "system_audio"'),
    ):
        assert track_id in source
        assert "capture_epoch" in source
        assert "track_sequence" in source
        assert "observed_at_unix_ms" in source
        assert "health_status" in source
        assert "raw_audio_uploaded: false" in source
        assert "calls_remote_provider: false" in source


def test_next002_tauri_permissions_are_generated_for_each_new_command() -> None:
    command_source = COMMAND_MANIFEST.read_text(encoding="utf-8")
    commands = (
        "dual_track_adapter_start",
        "dual_track_adapter_status",
        "dual_track_adapter_collect_events",
        "dual_track_adapter_stop",
        "dual_track_adapter_cleanup",
        "mic_adapter_cleanup",
        "system_audio_adapter_cleanup",
    )

    for command in commands:
        assert f'"{command}"' in command_source
        permission = TAURI_ROOT / "permissions" / "autogenerated" / f"{command}.toml"
        permission_source = permission.read_text(encoding="utf-8")
        slug = command.replace("_", "-")
        assert f'identifier = "allow-{slug}"' in permission_source
        assert f'commands.allow = ["{command}"]' in permission_source
        assert f'identifier = "deny-{slug}"' in permission_source
        assert f'commands.deny = ["{command}"]' in permission_source
