import {
  Activity,
  ArrowRight,
  AudioLines,
  BadgeCheck,
  CalendarClock,
  Check,
  CircleAlert,
  CircleCheck,
  Clock3,
  Code2,
  Copy,
  Crosshair,
  DatabaseBackup,
  Download,
  ExternalLink,
  FileSearch,
  FileText,
  Hand,
  History,
  Home,
  Info,
  ListChecks,
  Mail,
  Menu,
  MessageSquareMore,
  Mic,
  Pause,
  Play,
  Radar,
  ScanSearch,
  ShieldCheck,
  Sparkles,
  TextSelect,
  UserRound,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-right': ArrowRight,
  'audio-lines': AudioLines,
  'badge-check': BadgeCheck,
  'calendar-clock': CalendarClock,
  check: Check,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'clock-3': Clock3,
  'code-2': Code2,
  copy: Copy,
  crosshair: Crosshair,
  'database-backup': DatabaseBackup,
  download: Download,
  'external-link': ExternalLink,
  'file-search': FileSearch,
  'file-text': FileText,
  hand: Hand,
  history: History,
  home: Home,
  info: Info,
  'list-checks': ListChecks,
  mail: Mail,
  menu: Menu,
  'message-square-more': MessageSquareMore,
  mic: Mic,
  pause: Pause,
  play: Play,
  radar: Radar,
  'scan-search': ScanSearch,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  'text-select': TextSelect,
  'user-round': UserRound,
  x: X,
}

type IconProps = LucideProps & {
  name: string
}

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = iconMap[name] || CircleAlert
  return <IconComponent aria-hidden="true" {...props} />
}
